[build]
builder = "DOCKERFILE"
buildCommand = "npm run build && cd dashboard && npm run build"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

