[build]
builder = "DOCKERFILE"
buildCommand = "npm run build && cd dashboard && npm run build"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[nixpacks]
nodejs = "18"
